[server]
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#171918"
backgroundColor = "#EFEFE9"
secondaryBackgroundColor = "#E6E7E1"
textColor = "#171918"
font = "sans-serif"
